[package]
name = "openai-api-rs"
version = "5.0.10"
edition = "2021"
authors = ["Dongri Jin <dongrium@gmail.com>"]
license = "MIT"
description = "OpenAI API client library for Rust (unofficial)"
repository = "https://github.com/dongri/openai-api-rs"

[dependencies]
async-channel = "1.8.0"
eventsource-stream = "0.2.3"
reqwest = { version = "0.11.13", features = ["json", "stream"] }
tokio = { version = "1.32.0", default-features = false, features = ["macros", "rt", "sync"] }
futures = "0.3.25"
futures-util = "0.3.25"
anyhow = "1.0.75"
bytes = "1.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["default-tls"]
rustls = ["reqwest/rustls-tls"]
default-tls = ["reqwest/default-tls"]

[dependencies]
tokio-tungstenite = "0.24.0"
tungstenite = "0.24.0"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["charset", "http2", "json", "multipart", "socks"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[dependencies.bytes]
version = "1.7.1"
